version: 2
jobs:
   build:
     working_directory: ~/build
     machine:
        image: circleci/classic:edge
     steps:
        - checkout:
            path: $CIRCLE_PROJECT_REPONAME
        - run:
             name: Build userservice
             shell: /bin/bash
             command: |
                cd ~
                cp build/$CIRCLE_PROJECT_REPONAME/build.sh build
                cp build/$CIRCLE_PROJECT_REPONAME/config.sh build
                cd build
                ./build.sh
        - run:
             name: Push image to Dockerhub
             shell: /bin/bash
             command: |	
                if [[ $CIRCLE_BRANCH == "master" ]]; then
                    TAG=0.1.$CIRCLE_BUILD_NUM
                    docker build -f userservice/Dockerfile -t rounakraj8/userservice .
                    docker login -u $DOCKER_USER -p $DOCKER_PASS
                    
                    # Tag and push image for each additional tag
                    for tag in {${TAG},latest}; do  
                      docker tag rounakraj8/userservice rounakraj8/userservice:${tag}
                      docker push rounakraj8/userservice:${tag}
                    done
                fi
             
